#include <iostream>

using namespace std;

int main()
{
    freopen("sorting.out", "w", stdout);
    cout << "3\nS 0 _ _ -> S _ > 0 > 0 >\nS 1 _ _ -> S _ > 1 > 1 >\nS | _ _ -> S _ > | > | >\nS _ _ _ -> M _ ^ | ^ | <\n\nM _ | 0 -> M _ ^ | ^ 1 <\nM _ | 1 -> N _ ^ | < 0 <\nM _ | | -> C _ ^ | < | >\nM _ | x -> C _ ^ | < x >\nM _ | _ -> C _ ^ | < _ >\n\nC _ 0 1 -> C _ ^ 0 < 1 >\nC _ 1 1 -> C _ ^ 1 < 1 >\nC _ x | -> CPY _ ^ x > | ^\nC _ | | -> CPY _ ^ | > | ^\nC _ _ | -> CPY _ ^ _ > | ^\n\nCPY _ 0 | -> CPY 0 > 0 > | ^\nCPY _ 1 | -> CPY 1 > 1 > | ^\nCPY _ | | -> N | > x < x <\n\nN _ 0 0 -> N _ ^ 0 < 0 <\nN _ 0 1 -> N _ ^ 0 < 1 <\nN _ 1 0 -> N _ ^ 1 < 0 <\nN _ 1 1 -> N _ ^ 1 < 1 <\nN _ 0 | -> N _ ^ 0 < | ^\nN _ 1 | -> N _ ^ 1 < | ^\nN _ | | -> M _ ^ | ^ | <\nN _ x 0 -> N _ ^ x < 0 < \nN _ x 1 -> N _ ^ x < 1 <\nN _ x | -> N _ ^ x < | ^\nN _ 0 x -> N _ ^ 0 < x <\nN _ 1 x -> N _ ^ 1 < x <\nN _ | x -> N _ ^ | ^ x <\nN _ x x -> N _ ^ x < x <\nN _ x _ -> R _ ^ 0 > _ >\nN _ 0 _ -> R _ ^ 0 > _ >\nN _ 1 _ -> R _ ^ 1 > _ >\nN _ _ x -> R _ ^ _ > x >\nN _ _ 0 -> R _ ^ _ > 0 >\nN _ _ 1 -> R _ ^ _ > 1 >\nN _ _ _ -> R _ ^ _ > _ >\n\nR _ 0 0 -> R _ ^ 0 > 0 >\nR _ 0 1 -> R _ ^ 0 > 1 >\nR _ 1 0 -> R _ ^ 1 > 0 >\nR _ 1 1 -> R _ ^ 1 > 1 >\nR _ | 0 -> RP _ ^ | > 0 >\nR _ | 1 -> RP _ ^ | > 1 >\nR _ 0 | -> RP _ ^ 0 > | >\nR _ 1 | -> RP _ ^ 1 > | >\nR _ | | -> RP _ ^ | > | >\nR _ x 0 -> R _ ^ x > 0 > \nR _ x 1 -> R _ ^ x > 1 >\nR _ x | -> RP _ ^ x > | >\nR _ 0 x -> R _ ^ 0 > x >\nR _ 1 x -> R _ ^ 1 > x >\nR _ | x -> RP _ ^ | > x >\nR _ x x -> R _ ^ x > x >\nR _ _ 0 -> R _ ^ _ ^ 0 >\nR _ _ 1 -> R _ ^ _ ^ 1 >\nR _ _ | -> RP _ ^ _ ^ | >\nR _ _ x -> R _ ^ _ ^ x >\nR _ 0 _ -> R _ ^ 0 > _ ^\nR _ 1 _ -> R _ ^ 1 > _ ^\nR _ x _ -> R _ ^ x > _ ^\nR _ | _ -> RP _ ^ | > _ ^\nR _ _ _ -> END _ < _ ^ _ ^\n\nEND | _ _ -> ENDL _ < _ ^ _ ^\n\nENDL 0 _ _ -> ENDL 0 < _ ^ _ ^\nENDL 1 _ _ -> ENDL 1 < _ ^ _ ^\nENDL | _ _ -> ENDL | < _ ^ _ ^\nENDL _ _ _ -> AC _ > _ ^ _ ^\n\nRP _ 0 0 -> RP _ ^ 0 > 0 >\nRP _ 0 1 -> RP _ ^ 0 > 1 >\nRP _ 1 0 -> RP _ ^ 1 > 0 >\nRP _ 1 1 -> RP _ ^ 1 > 1 >\nRP _ | 0 -> RP _ ^ | > 0 >\nRP _ | 1 -> RP _ ^ | > 1 >\nRP _ 0 | -> RP _ ^ 0 > | >\nRP _ 1 | -> RP _ ^ 1 > | >\nRP _ | | -> RP _ ^ | > | >\nRP _ x 0 -> RP _ ^ x > 0 > \nRP _ x 1 -> RP _ ^ x > 1 >\nRP _ x | -> RP _ ^ x > | >\nRP _ 0 x -> RP _ ^ 0 > x >\nRP _ 1 x -> RP _ ^ 1 > x >\nRP _ | x -> RP _ ^ | > x >\nRP _ x x -> RP _ ^ x > x >\nRP _ _ 0 -> RP _ ^ _ ^ 0 >\nRP _ _ 1 -> RP _ ^ _ ^ 1 >\nRP _ _ | -> RP _ ^ _ ^ | >\nRP _ _ x -> RP _ ^ _ ^ x >\nRP _ 0 _ -> RP _ ^ 0 > _ ^\nRP _ 1 _ -> RP _ ^ 1 > _ ^\nRP _ x _ -> RP _ ^ x > _ ^\nRP _ | _ -> RP _ ^ | > _ ^\nRP _ _ _ -> N _ ^ _ < _ <\n" << flush;
    return 0;
}
